server:
  port: 7071
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: scott
    password: tiger
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.Oracle10gDialect
 
  mvc:
    view:
      prefix: /views/
      suffix: .jsp